service: phpeste-2018

provider:
  name: openwhisk
  runtime: php

package:
  individually: true
  exclude:
    - "*"
  include:
    - "vendor/**"

functions:

  entrypoint:
    handler: index.entrypoint
    annotations:
      web-export: true
    package:
      include:
        - index.php

  health-check:
    handler: health-check.status
    annotations:
      web-export: true
    package:
      include:
        - health-check.php

plugins:
  - serverless-openwhisk

